# Generated by Django 3.2 on 2021-05-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shot_desc', models.CharField(max_length=350)),
                ('long_desc', models.CharField(max_length=600)),
                ('thumbnail', models.CharField(max_length=500)),
                ('video_url', models.CharField(max_length=400)),
            ],
        ),
    ]
